version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Vk123
      MYSQL_DATABASE: server
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spring-net

  app:
    build: .
    container_name: spring-app
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/server
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Vk123
    networks:
      - spring-net

volumes:
  mysql_data:

networks:
  spring-net:
